# # //route pour tester GET /:artiste_id/oeuvres
GET http://localhost:3000/1/oeuvres
COntent-Type:application/json

#Récupération des 3 oeuvres pour la page d'accueil
# GET http://localhost:3000/1/oeuvres-homePage
# COntent-Type:application/json

//test téléchargement oeuvre à faire dans Insomnia avec multi-part et file

//route pour tester GET/:artiste_id/oeuvres/:oeuvre_id
//Récupérer les détails de l’oeuvre par son id

# GET http://localhost:3000/1/oeuvres/60
# COntent-Type:application/json


# PATCH http://localhost:3000/1/oeuvres/60
# Content-Type:application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MQ.W6PGTCJ5oubFUOAV8VWOoh8_SzmiMcBzDzWunPTtlKw

# {
#   "name": "Rochelle",
#   "description": "photo de Rochelle Flatley",
#   "production_year": "2020-08-10T22:00:00.000Z",
#   "technique": "Sepia",
#   "width": 20,
#   "height": 90,
#   "media": "papier mat",
#   "framing": true,
#   "quote": "la beauté...",
#   "path": "https://media.istockphoto.com/id/496619649/fr/photo/beaut%C3%A9-asiatique.jpg?s=2048x2048&w=is&k=20&c=-czWG2a8ohzEgBDXXujSNFWvM0W8LBinsp8Iy2fX1oo=",
#   "orientation": "portrait",
#   "position": 1,
#   "categories": "Personnes,Mariage"   
# }



# POST http://localhost:3000/1/oeuvres
# Content-Type:application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MQ.W6PGTCJ5oubFUOAV8VWOoh8_SzmiMcBzDzWunPTtlKw

# {
    
#     "name": "test",
#     "description": "à supprimer",

#     "production_year": "2021-12-08T23:00:00.000Z",
#     "technique": "argentique",
   
#     "height": 40,
#     "media": "toile",
#     "framing": false,
#     "path": "https://media.istockphoto.com/id/1293643267/fr/photo/statue-antique-3d-de-femme-pierre-cass%C3%A9e-blanche-grec-mod%C3%A8le-romain-de-bont%C3%A9-bouquet-rose-de.jpg?s=2048x2048&w=is&k=20&c=Vp-h3Ybo5O5hWGFV5WbKfpmaUm89SvWmKN_Z4gHtRoE=",
#     "orientation": "paysage",
#     "position": 3,
#     "homepage_flag": false,
#     "artist_id": 1
#   }


# # Route pour tester DELETE /:artiste_id/oeuvres/:oeuvre_id
# DELETE http://localhost:3000/1/oeuvres/96
# Content-Type:application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MQ.W6PGTCJ5oubFUOAV8VWOoh8_SzmiMcBzDzWunPTtlKw

# //modifie l'oeuvre d'id 23
# PATCH http://localhost:3000/1/oeuvres/23
# Content-Type:application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MQ.W6PGTCJ5oubFUOAV8VWOoh8_SzmiMcBzDzWunPTtlKw

# {
#     "name": "Edna Ortiz",
#     "description": "photo de Edna Ortiz",
#     "production_year": "2021-12-08T23:00:00.000Z",
#     "technique": "argentique",   
#     "height": 40,
#     "media": "toile",
#     "framing": false,
#     "path": "https://media.istockphoto.com/id/1293643267/fr/photo/statue-antique-3d-de-femme-pierre-cass%C3%A9e-blanche-grec-mod%C3%A8le-romain-de-bont%C3%A9-bouquet-rose-de.jpg?s=2048x2048&w=is&k=20&c=Vp-h3Ybo5O5hWGFV5WbKfpmaUm89SvWmKN_Z4gHtRoE=",
#     "orientation": "paysage",
#     "position": 3,
#     "homepage_flag": false
    
#   }

# # #   // Route pour tester DELETE /:artiste_id/categories/:categorie_id
# DELETE http://localhost:3000/1/oeuvres/15
# Content-Type:application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MQ.W6PGTCJ5oubFUOAV8VWOoh8_SzmiMcBzDzWunPTtlKw


# #Tests téléchargement
# POST http://localhost:3000/1/oeuvres/telechargement-oeuvre
# Content-Type:application/json

# {  
#   "name": "Rochelle Flatley",
#   "description": "photo de Rochelle Flatley",
#   "production_year": "2020-08-10T22:00:00.000Z",
#   "technique": "Sepia",
#   "width": 70,
#   "height": 90,
#   "media": "papier mat",
#   "framing": true,
#   "quote": "Je ne suis rien, je le sais",
#   "path": "https://media.istockphoto.com/id/496619649/fr/photo/beaut%C3%A9-asiatique.jpg?s=2048x2048&w=is&k=20&c=-czWG2a8ohzEgBDXXujSNFWvM0W8LBinsp8Iy2fX1oo=",
#   "orientation": "portrait",
#   "position": 1,
#   "homepage_flag": true,
#   "artist_id": 1,
#   "category_name":["Paysages", "Personnes"]
# }