# #route pour tester rapidement le signup mais en get 
# GET http://localhost:3000/signup

# pour tester la route /signup --> il faut les données au bon format BDD
# # # changer l'adresse email pour ne pas en avoir une déjà existante dans la BDD
# POST http://localhost:3000/signup
# content-type: application/json

# {
#   "path": "https://pixabay.com/fr/photos/femme-manteau-cam%C3%A9ra-photographe-7883774/",
#   "lastname": "Focus",
#   "firstname": "Emilie",
#   "email": "emilie.focus@example.com",
#   "password": "Emilie21@",
#   "birthdate": "1987-07-10",
#   "biography": "Emilie Focus est une photographe passionnée par la capture de moments uniques et la création d'images qui transmettent des   émotions intenses. Son travail artistique se concentre sur l'exploration de la lumière, de la composition et des perspectives pour créer des   œuvres qui captivent et inspirent",
#   "type": "Photographe",
#   "street_no": "12",
#   "street_name": "avenue de l'objectif",
#   "zipcode": "75005",
#   "city": "Paris",
#   "phone": "+33656789012",
#   "facebook": "https://www.facebook.com/",
#   "insta": "https://www.instagram.com/",
#   "twitter": "https://twitter.com/home",
#   "youtube": "https://www.youtube.com/",
#   "role_id": 1
# }

# pour tester la route /signup --> il faut les données au bon format BDD
# # changer l'adresse email pour ne pas en avoir une déjà existante dans la BDD
# POST http://localhost:3000/signup
# content-type: application/json

# {
#   "path": "https://picsum.photos/seed/picsum/200/300",
#   "lastname": "marre",
#   "firstname": "des fonctions",
#   "email": "marredesfonctions@loremipsum.com",
#   "password": "Julie21@",
#   "type": "photograph",
#   "role_id": 1
# }


# //OK route pour tester signin avec génération token 
POST http://localhost:3000/signin
Content-Type:application/json

{"email": "emilie.focus@example.com",  "password": "Emilie21@"}

# # {"email": "nelly.dubois@loremipsum.com",  "password": "Passw0rd*"}

# {"email": "aurelie.blanc@loremipsum.com",  "password": "Aurelie0!"}



# #OK tester une route get avec headers incluant le token
# # GET http://localhost:3000/signup
# # Content-Type:application/json
# # Authorization: Bearer $2b$10$nEJVD3r0NhrdBeKWyqOR9u5KdfVVlveNdFN67RjNCezKhcWpcAAGu
