# #route pour tester rapidement le signup mais en get 
# GET http://localhost:3000/signup

# pour tester la route /signup --> il faut les données au bon format BDD
# # changer l'adresse email pour ne pas en avoir une déjà existante dans la BDD
# POST http://localhost:3000/signup
# content-type: application/json

# {
#   "path": "https://picsum.photos/seed/picsum/200/300",
#   "lastname": "Zaccaria",
#   "firstname": "Julie",
#   "email": "julie@loremipsum.com",
#   "password": "Julie21@",
#   "birthdate": "1990-10-01",
#   "biography": "lorem ipsum",
#   "type": "photograph",
#   "street_no": "4",
#   "street_name": "avenue",
#   "zipcode": "77600",
#   "city": "Meaux",
#   "phone": "0492651726",
#   "facebook": "https://www.facebook.com/",
#   "insta": "https://www.instagram.com/",
#   "twitter": "https://twitter.com/home",
#   "youtube": "https://www.youtube.com/",
#   "role_id": 1
# }

# pour tester la route /signup --> il faut les données au bon format BDD
# # changer l'adresse email pour ne pas en avoir une déjà existante dans la BDD
# POST http://localhost:3000/signup
# content-type: application/json

# {
#   "path": "https://picsum.photos/seed/picsum/200/300",
#   "lastname": "marre",
#   "firstname": "des fonctions",
#   "email": "marredesfonctions@loremipsum.com",
#   "password": "Julie21@",
#   "type": "photograph",
#   "role_id": 1
# }


//OK route pour tester signin avec génération token 
POST http://localhost:3000/signin
Content-Type:application/json

# {"email": "nelly.dubois@loremipsum.com",  "password": "Passw0rd*"}

{"email": "aurelie.blanc@loremipsum.com",  "password": "Aurelie0!"}



# #OK tester une route get avec headers incluant le token
# # GET http://localhost:3000/signup
# # Content-Type:application/json
# # Authorization: Bearer $2b$10$nEJVD3r0NhrdBeKWyqOR9u5KdfVVlveNdFN67RjNCezKhcWpcAAGu
