# //route pour tester GET /:artiste_id
GET http://localhost:3000/1
Content-Type:application/json

# # //route pour tester PATCH /:artist_id
# PATCH http://localhost:3000/5
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MQ.W6PGTCJ5oubFUOAV8VWOoh8_SzmiMcBzDzWunPTtlKw

# {   
#     "lastname": "Zaccaria",
#     "firstname": "Julie",
#     "email": "julie.zaccaria@loremipsum.com",
#     "password": "Mdp60-ab",
#     "path": "https://picsum.photos/seed/picsum/200/300",
#     "biography": "lorem ipsumipsum",
#     "birthdate": "1990-11-10",
#     "type": "photograph",
#     "street_no": null,
#     "street_name": null,
#     "zipcode": null,
#     "city": null,
#     "phone": null,
#     "facebook": null,
#     "insta": null,
#     "twitter": null,
#     "youtube": null
# }

# GET http://localhost:3000/7
# # Content-Type:application/json

# PATCH http://localhost:3000/7
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MQ.W6PGTCJ5oubFUOAV8VWOoh8_SzmiMcBzDzWunPTtlKw

# { 
#     "biography":"il était une fois",
  
#   "path": "https://picsum.photos/seed/picsum/200/300",
#   "artistid": 7,
#   "path": "https://picsum.photos/seed/picsum/200/300",
#   "lastname": "marre",
#   "firstname": "des fonctions",
#   "email": "marredesfonctions@loremipsum.com",
#   "password": "$2b$10$V6lUu0DA6keO2ua.FO5Us.hDDOSsIV1EpHElDwsw4avesNxzFri62",
#   "biography": null,
#   "role_id": 1,
#   "created_at": "2024-02-15T20:12:19.198Z",
#   "updated_at": null,
#   "artist_detailsid": 7,
#   "birthdate": null,
#   "type": "photograph",
#   "zipcode": null,
#   "city": null,
#   "phone": null,
#   "facebook": null,
#   "insta": null,
#   "twitter": null,
#   "youtube": null,
 
#   "created_atdetails": null,
#   "updated_atdetails": null
# }
